name: Build-CrossPlatform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Restore dependencies
      run: dotnet restore src
    
    - name: Build
      run: dotnet build src --no-restore
    
    - name: Run tests
      run: dotnet test src --no-build --verbosity normal

    - name: Pack NuGet packages
      run: dotnet pack src --configuration Release --output ./nupkgs

    - name: Publish to NuGet (only on main)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        dotnet nuget push ./nupkgs/GTMH.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
